import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto flex flex-col justify-center items-center space-y-10">{children}</body>
    </html>
  )
}
